#!/usr/bin/python 
# -*- coding: UTF-8 -*- 


#--------------cpp-------------------
ENV_CPP = Environment(CC = 'g++')

#compile info
TARGETNAME = 'proxyservice'
LIB = Split('ACE pthread libBroker jsoncpp protobuf amqpcpp DMMessage')
FILELIST = Glob('*.cpp')
FILELIST = FILELIST
HEADFILEPATH = Split('../../3rd ../../common ../../message ../../3rd/amqpcpp')
LIB_DIR = Split('../Thrid/lib ../Common ../LibMessage')
FLAGS = Split('-std=c++11 -Wall -g -D _DEBUG')

#Program target
TARGETFILE = ENV_CPP.Program(target = TARGETNAME,source = FILELIST,LIBS = LIB,CPPPATH = HEADFILEPATH,LIBPATH = LIB_DIR,CCFLAGS = FLAGS)

#install
INSTALL = ENV_CPP.Install('../bin', TARGETFILE)
ENV_CPP.Alias('release',INSTALL)
